# description: configuration file path, if it's specified as relative path,
# then directory of binary file will be the base directory of configuration file,
# it is recommended to specify absolute path.
# command-line-argument: --config
# type: string
# default: None
config: go_template_cli.yaml

# log configuration
log:
  # description: log level
  # type: string
  # available: [debug, info, warn, error, fatal]
  # default: info
  level: info
  # description: log format
  # type: string
  # available: [text, json]
  # default: text
  format: text

# mod configuration
mod:
  # description: mod directory
  # type: string
  # default: None
  dir: ""
  # description: mod name
  # type: string
  # default: None
  name: ""
  # description: mod version
  # type: string
  # default: None
  version: ""
